@BASE_URL = http://localhost:8004
@API_VERSION = api/v1
@JSON = application/json
@AUTH_TOKEN = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkZDA1MzcyNS1kMmY0LTQ4YTgtODkwYS02ZGZjZGIwZjQyNGIiLCJlbWFpbCI6InRlc3QxQGdtYWlsLmNvbSIsImlhdCI6MTc2ODU4Mzc3MSwiZXhwIjoxNzY4NTg3MzcxfQ.gvGWOUapkfV7Qv3XpzIJMcdixzNtnNLN84c9WSYGxb0

### Auth Service Health Check
GET {{BASE_URL}}/{{API_VERSION}}/auth/health

### Create User
POST {{BASE_URL}}/{{API_VERSION}}/auth/user/create-user
Content-Type: {{JSON}}

{
    "firstName" : "Test Third",
    "middleName" : "User Third",
    "lastName" : "3",
    "email" : "test3@gmail.com",
    "password" : "1234"
}

### Login User
POST {{BASE_URL}}/{{API_VERSION}}/auth/user/login-user
Content-Type: {{JSON}}

{
    "email" : "test1@gmail.com",
    "password" : "1234"
}

### Get User Details
GET {{BASE_URL}}/{{API_VERSION}}/auth/user/get-user-details
Authorization: {{AUTH_TOKEN}}
