@BASE_URL = http://localhost:8004
@API_VERSION = api/v1
@JSON = application/json
@AUTH_TOKEN = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhM2FhMWI5Yy03MjYzLTQ2MTEtOTdiZS03MWVjNTA3NWY3OTYiLCJpYXQiOjE3Njg3MjM1NDUsImV4cCI6MTc2ODcyNzE0NX0.6wzGmEEs1L98IqGojMs4CiXlNSJCiboaN34TB2E2ayw

### Auth Service Health Check
GET {{BASE_URL}}/{{API_VERSION}}/auth/health

### Create User
POST {{BASE_URL}}/{{API_VERSION}}/auth/user/create-user
Content-Type: {{JSON}}

{
    "firstName" : "Test First",
    "middleName" : "User First",
    "lastName" : "1",
    "email" : "test1@gmail.com",
    "password" : "1234"
}

### Login User
POST {{BASE_URL}}/{{API_VERSION}}/auth/user/login-user
Content-Type: {{JSON}}

{
    "email" : "test1@gmail.com",
    "password" : "1234"
}

### Get User Details
GET {{BASE_URL}}/{{API_VERSION}}/auth/user/get-user-details
Authorization: {{AUTH_TOKEN}}
